#!/usr/bin/env python3
"""Build quick/p0.md: every P0 check in one file, for "quick vibe check".

  python3 scripts/build-quick.py          write quick/p0.md
  python3 scripts/build-quick.py --check  exit 1 if quick/p0.md is out of date (used by CI)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "quick" / "p0.md"
MANUAL = ROOT / "quick" / "manual.txt"

# Section title per source folder or file, in output order.
SECTIONS = [
    ("00-universal", "Every project"),
    ("00-universal/payments.md", "If the app takes payments"),
    ("00-universal/llm-features.md", "If the app calls a language model"),
    ("00-universal/cloud-infra.md", "If the repo has cloud or deploy config"),
    ("01-frontend/_common", "Frontend (any)"),
    ("01-frontend/react", "React / Next.js"),
    ("01-frontend/angular", "Angular"),
    ("01-frontend/vue", "Vue"),
    ("01-frontend/vanilla-js", "Plain JS"),
    ("02-backend/_common", "Backend (any)"),
    ("02-backend/dotnet", ".NET"),
    ("02-backend/java-spring", "Java Spring"),
    ("02-backend/node", "Node.js"),
    ("02-backend/python", "Python"),
    ("02-backend/supabase", "Supabase"),
    ("02-backend/firebase", "Firebase"),
    ("03-mobile/_common", "Mobile (any)"),
    ("03-mobile/android-native", "Android (Kotlin)"),
    ("03-mobile/ios-native", "iOS (Swift)"),
    ("03-mobile/react-native-expo", "React Native / Expo"),
    ("03-mobile/flutter", "Flutter"),
    ("04-release/google-play.md", "Release: Google Play"),
    ("04-release/app-store.md", "Release: App Store"),
    ("04-release/web-deploy.md", "Release: web"),
]
SKIP = {"00-universal/pre-launch-checklist.md", "00-universal/README.md"}


def section_of(rel):
    best = None
    for key, title in SECTIONS:
        if rel == key or rel.startswith(key + "/"):
            if best is None or len(key) > len(best[0]):
                best = (key, title)
    return best[1] if best else None


def p0_items(path):
    """Yield (id, text) for every P0 in a checklist or chronic-issues file."""
    section = None
    cur = None
    for line in path.read_text().splitlines():
        m = re.match(r"^## (P[012])", line)
        if m:
            section = m.group(1)
        m = re.match(r"^### ([A-Z0-9]+-\d{3}) · (.*)", line)
        if m:
            cur = {"id": m.group(1), "title": m.group(2)}
            continue
        if cur:
            m = re.match(r"^\*\*Severity:\*\* (P[012])", line)
            if m:
                cur["sev"] = m.group(1)
            m = re.match(r"^\*\*How to test:\*\* (.*)", line)
            if m:
                if cur.get("sev") == "P0":
                    yield cur["id"], f"{cur['title']}. Test: {m.group(1)}"
                cur = None
            continue
        m = re.match(r"^- \[ \] `([A-Z0-9]+-\d{3})`(?: \*\*(P[012])\*\*)? (.*)", line)
        if m and (m.group(2) or section) == "P0":
            yield m.group(1), m.group(3)


def build():
    manual = {
        line.strip()
        for line in MANUAL.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }
    groups = {title: [] for _, title in SECTIONS}
    seen = set()
    for path in sorted(ROOT.glob("0*/**/*.md")):
        rel = path.relative_to(ROOT).as_posix()
        if rel in SKIP or path.name == "README.md":
            continue
        title = section_of(rel)
        if title is None:
            sys.exit(f"No section for {rel}; add it to SECTIONS in scripts/build-quick.py")
        for cid, text in p0_items(path):
            seen.add(cid)
            tag = "manual · " if cid in manual else ""
            groups[title].append(f"- `{cid}` {tag}{text}")
    unknown = sorted(manual - seen)
    if unknown:
        sys.exit(f"quick/manual.txt lists IDs that are not P0 checks: {', '.join(unknown)}")

    out = [
        "# Quick mode: every P0 check",
        "",
        "Generated by `scripts/build-quick.py` from the checklists. Do not edit by hand.",
        "`manual` = can't be verified from code (device, store console, production, a running build).",
        "",
    ]
    for _, title in SECTIONS:
        if groups[title]:
            out += [f"## {title}", ""] + groups[title] + [""]
    return "\n".join(out)


def main():
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("quick/p0.md is out of date. Run: python3 scripts/build-quick.py")
            sys.exit(1)
        print("quick/p0.md is up to date.")
        return
    OUT.write_text(text)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
